version: "3.5"
services:
    vbox_http:
        container_name: vbox_http
        image: joweisberg/phpvirtualbox
        restart: always
#        depends_on:
#            - vbox_websrv
        ports:
            - 8080:80
        environment:
            TZ: "Asia/Kolkata"
            SRV1_HOSTPORT: "192.168.2.5:18083"
            SRV1_NAME: "Server1"
            SRV1_USER: "subhrendu"
            SRV1_PW: "265555"
            CONF_browserRestrictFolders: "/home,/usr/lib/virtualbox,"
            CONF_noAuth: "true"

    vbox_websrv:
        container_name: vbox_websrv_1
        image: jazzdd/vboxwebsrv
        command: subhrendu@192.168.2.5
        restart: always
        environment:
            - USE_KEY: 1
        volumes:
            - "./ssh:/root/.ssh"