version: "3"
services:
    vbox_http:
        container_name: vbox_http
        image: joweisberg/phpvirtualbox
        restart: always
        depends_on:
            - vbox_websrv
        ports:
            - 8080:80
        environment:
            TZ: "Asia/Kolkata"
            SRV1_HOSTPORT: "vbox_websrv_1:18083"
            SRV1_NAME: "Server1"
            SRV1_USER: "user1"
            SRV1_PW: "test"
            CONF_browserRestrictFolders: "/home,/usr/lib/virtualbox,"
            CONF_noAuth: "true"

    vbox_websrv:
        container_name: vbox_websrv_1
        build:
            context: .
            dockerfile: Dockerfile-vboxwebsrv
        image: vboxwebsrv
        command: "subhrendu@192.168.0.103"
        #restart: always
        environment:
            - USE_KEY=1
            - SSH_PORT=22
            - SSH_PASSWD=265555
        volumes:
            #- "./ssh:/root/.ssh"
            - "./init_run.sh:/run.sh"
        network_mode: host
        #stdin_open: true
        #tty: true
        #entrypoint: ["bash"]
        #command: ["tail", "-f", "/dev/null"]
